# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 兼一书虫
subtitle: '一日千里'
description: '挑战时没有失败<br>放弃时才是失败'
keywords: server,frontend,backend,hexo
author: narutohyc
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
# url: https://github.com/hycBook/hycBlog.git
url: https://hycbook.github.io/hycBlog
# 生成文章唯一链接
# permalink: :year/:month/:day/:title/
# permalink: article/:title/
permalink: article/:abbrlink.html # post为自定义前缀
abbrlink:
  alg: crc16   #算法： crc16(default) and crc32
  rep: dec     #进制： dec(default) and hex
root: /

permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false

# 资源路径问题
post_asset_folder: true
marked:
  prependRoot: false
  postAsset: false
relative_link: false

future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly # landscape

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: 
    # github: git@github.com:hycBook/hycBlog.git
    coding: https://narutohyc.coding.net/p/hexo/d/hycblog/git
  # example, https://github.com/hexojs/hexojs.github.io
  branch: gh-pages
  name: narutohyc
  email: 1832044043@qq.com


# algolia搜索插件
algolia:
  appId: "IMKX0J251S"
  apiKey: "92de3dc43df2b8318c81df68e94d2221"
  adminApiKey: "1981da031c9547f201aa1622c2e3aaf1"
  chunkSize: 5000
  indexName: hexo_book
  fields:
    - content:strip:truncate,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title

# B站追番配置
bangumi:
  enable: true 
  vmid: 121853877
  title: '生命不息，追番不止！'
  quote: 'Where there is life, there is life.'
  show: 1
  loading: '/img/bangumi-loading.gif'



# 双栏布局插件引入
butterfly_article_double_row:
  enable: true

# Math 數學
# markdown:
#   plugins:
#     - plugin:
#       name: '@neilsustc/markdown-it-katex'
#       options:
#         strict: false
#         

# Math 数学
kramed:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true    


# 在主配置_config.yml或者主题配置_config.butterfly.yml文件中引入配置项
# envelope_comment
# see https://akilar.top/posts/58900a8/
# 留言板信封  https://blog.imzjw.cn/posts/b74f504f
envelope_comment:
  enable: true #开关
  cover: https://ae01.alicdn.com/kf/U5bb04af32be544c4b41206d9a42fcacfd.jpg #信笺封面图
  message: #信笺内容，支持多行
    - 有什么想问的？
    - 有什么想说的？
    - 有什么想吐槽的？
    - 哪怕是有什么想吃的，都可以告诉我哦~
  bottom: 自动书记人偶竭诚为您服务！ #信笺结束语，只能单行
  height: #调整信笺划出高度，默认1050px
  path: #【可选】comments 的路径名称。默认为 comments，生成的页面为 comments/index.html
  front_matter: #【可选】comments页面的 front_matter 配置
    title: 留言板
    comments: true