name: Deployment

on:
  push:
    branches: [main] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        
        # echo 使用 Hexo-abbrlink生成唯一文章链接
        # npm install hexo-abbrlink --save
        
        # Math 数学
        npm uninstall hexo-renderer-marked --save
        npm install hexo-renderer-kramed --save
        # npm un hexo-renderer-marked --save # 如果有安裝這個的話，卸載
        # npm un hexo-renderer-kramed --save # 如果有安裝這個的話，卸載
        # npm i hexo-renderer-markdown-it --save # 需要安裝這個渲染插件
        # npm install @neilsustc/markdown-it-katex --save #需要安裝這個katex插件

        # 添加字数统计
        npm install hexo-wordcount --save

        echo 安装algolia搜索库
        # 配置algolia环境参数
        export HEXO_ALGOLIA_INDEXING_KEY=${{ secrets.ALGOLIA_TOKEN }}
        npm install hexo-algoliasearch --save

        # 給 hexo-theme-butterfly 添加 Artitalk 説説
        npm install hexo-butterfly-artitalk

        # Hexo哔哩哔哩番剧页面插件
        npm install hexo-bilibili-bangumi --save

        # 双栏布局插件引入
        npm i hexo-butterfly-article-double-row --save

        echo 开始修改文件资源路径
        cd source/_posts
        python dir_change.py
        rm -rf java
        rm -rf common
        rm -rf python
        rm -rf english
        rm -rf math
        mv target_dir/* .
        cd ../..
        echo 修改文件资源路径完成
        # cp nodejs/hexo-renderer-marked/lib/renderer.js node_modules/hexo-renderer-marked/lib/

        # 执行编译
        hexo clean
        hexo bangumi -u # 更新番剧数据
        hexo g
        mv source/_posts/target_dir_img/* public/img/
        # 修改非首页的top图片的高度
        echo '#page-header.post-bg {  height: 600px; }' >> public/css/index.css
        echo '#page-header.not-home-page {  height: 600px;}' >> public/css/index.css
        hexo algolia

    - name: Deploy #步骤4：把编译好的静态目录上传到gh-pages分支上
      uses: JamesIves/github-pages-deploy-action@3.1.5 #这里调用第三方依赖，用于上传代码到指定分支上
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages #github pages 默认的分支
        FOLDER: public #上传文件的目录，我这个目录在根目录下，如果是子目录可以这么写  docs/.vuepress/dist
        clean: true