name: Deployment

on:
  push:
    branches: [main] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      CODING_USERNAME: ${{ secrets.CODING_USERNAME }}
      CODING_PASSWORD: ${{ secrets.CODING_PASSWORD }}
      # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
      SSH_PRIVATE_KEY: ${{ secrets.CODING_PASSWORD }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        # npm install hexo-deployer-git --save

        # echo 使用 Hexo-abbrlink生成唯一文章链接
        npm install hexo-abbrlink --save
        
        # Math 数学
        npm uninstall hexo-renderer-marked --save
        npm install hexo-renderer-kramed --save

        # 添加字数统计
        npm install hexo-wordcount --save

        echo 安装algolia搜索库
        # 配置algolia环境参数
        export HEXO_ALGOLIA_INDEXING_KEY=${{ secrets.ALGOLIA_TOKEN }}
        npm install hexo-algoliasearch --save

        # 給 hexo-theme-butterfly 添加 Artitalk 説説
        npm install hexo-butterfly-artitalk --save

        # Hexo哔哩哔哩番剧页面插件
        npm install hexo-bilibili-bangumi-plus --save

        # 双栏布局插件引入
        npm i hexo-butterfly-article-double-row --save
        
        # 插入b站的视频卡片
        # npm i hexo-bilibili-card --save

        # gulp 压缩   https://blog.imzjw.cn/posts/b74f504f/#gulp-%E5%8E%8B%E7%BC%A9  会影响Hexo哔哩哔哩番剧页面插件
        # 压缩html插件
        npm install gulp-htmlclean --save-dev
        npm install --save gulp-htmlmin
        # 压缩css插件
        npm install gulp-clean-css --save-dev
        # 压缩js插件
        # 使用babel压缩js，与terser二选一
        npm install --save-dev gulp-uglify
        npm install --save-dev gulp-babel @babel/core @babel/preset-env
        # 压缩图片插件
        # npm install --save-dev gulp-imagemin


        # 配置PWA   https://akilar.top/posts/8f31c3d0/
        npm install --global gulp-cli # 全局安装gulp命令集
        npm install workbox-build gulp --save # 安装workbox和gulp插件

        # 留言板信封
        npm install hexo-butterfly-envelope --save

        # 轮播置顶文章
        npm install hexo-butterfly-swiper --save

        # 分类磁贴
        npm install hexo-butterfly-categories-card --save

        # 安装pwa相关插件
        npm install hexo-offline --save

        # 生成站点地图
        npm install hexo-generator-sitemap --save
        npm install hexo-generator-baidu-sitemap --save

        # echo 开始修改文件资源路径
        # cd source/_posts
        # python dir_change.py
        # rm -rf java
        # rm -rf common
        # rm -rf python
        # rm -rf english
        # rm -rf math
        # mv target_dir/* .
        # cd ../..
        # echo 修改文件资源路径完成
        # cp nodejs/hexo-renderer-marked/lib/renderer.js node_modules/hexo-renderer-marked/lib/
        # 修改数学公式多行显示问题 https://www.uynajgi.com/919906d6.html
        # cp nodejs/kramed/lib/rules/inline.js node_modules/kramed/lib/rules/inline.js

        # 执行编译
        hexo clean
        hexo bangumi -u # 更新番剧数据
        hexo g
        # mv source/_posts/target_dir_img/* public/img/
        # 修改非首页的top图片的高度
        # cat themes/butterfly/source/css/hyc_font.css >> public/css/index.css
        # echo '#page-header.post-bg {  height: 800px; }' >> public/css/index.css
        # echo '#page-header.not-home-page {  height: 800px;}' >> public/css/index.css
        hexo algolia
        cp package-lock.json public/package-lock.json
        cp sitemaps/* >> public/
        gulp

    - name: Deploy #步骤4：把编译好的静态目录上传到gh-pages分支上  https://cloud.tencent.com/developer/article/1917861
      uses: JamesIves/github-pages-deploy-action@3.1.5 #这里调用第三方依赖，用于上传代码到指定分支上
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages #github pages 默认的分支
        FOLDER: public #上传文件的目录，我这个目录在根目录下，如果是子目录可以这么写  docs/.vuepress/dist
        clean: true
